version: '3.9'

services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["/venv/bin/python", "apps.py"]




