name: Cypress end to end Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django server in background
        env:
          SECRET_KEY: dummykey
        run: |
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8080 &

      - name: Wait for server to be ready
        run: |
          sleep 10
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080/home

     

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: ''
          wait-on: 'http://localhost:8080/home'
          wait-on-timeout: 60
